### ISSUE TITLE
Are the tests really working?

### ISSUE THREAD

**Issue by aseques** [jpscaletti/MailShake#10]
I just cloned the repository into my pc and I wanted to run the tests. In pycharm running under python 3.6, I get that 'No test were found', still the output is

> Ran 0 tests in 0.000s
> 
> OK
Also I saw that the link to the [travis CI](https://travis-ci.org/jpscaletti/Mailshake), that is currently broken.

**Comment by jpscaletti** [comment]
To run the test you need to use [py.test](https://www.jetbrains.com/help/pycharm/run-debug-configuration-py-test.html) 

The URL to Travis CI had a typo (the correct one is https://travis-ci.org/jpscaletti/MailShake)

**Comment by aseques** [comment]
Thanks, with your instructions and the latest commit they're working now.
