### ISSUE TITLE
Travis runs 0 test every time

### ISSUE THREAD

**Issue by aseques** [jpscaletti/MailShake#11]
I was looking into the logs for the travis CI, and they are not failing but they're neither running. For example with python 3.6 [here](https://travis-ci.org/jpscaletti/MailShake/jobs/325704797), [python 3.5](https://travis-ci.org/jpscaletti/MailShake/jobs/325704798), [python 2.7](https://travis-ci.org/jpscaletti/MailShake/jobs/325704799)

> ----------------------------------------------------------------------
> Ran 0 tests in 0.000s
> OK
> The command "python setup.py test" exited with 0.
> Done. Your build exited with 0.

On my pc when using the proper config, they run and pass.

**Comment by jpscaletti** [comment]
wow. I didn't realize they weren't running. Thank you! (I'll get to it)
