### ISSUE TITLE
Sending mail in HTML

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [jpscaletti/MailShake#12]
I've noticed that both examples of e-mails on your homepage are plain text e-mails. For one, it needs to be clear that this is possible. For another, I can't tell if the arguments `html` and `html_content` expected in `EmailMessage.__init__()` are equivalent or not. If they are, then the `html` argument is redundant.

**Comment by jpscaletti** [comment]
1. Yes it is possible using `html_content`
2. `text_content` and `html_content` parameters exists only for backwards compatibility and will be removed very soon. Use `text` and `html` instead.
3. You are right, the examples should be updated, and show more scenarios
